services:
  routing-updater:
    image: ghcr.io/indie-master/remnawave-routing-update:latest
    build: .
    container_name: remna-routing-updater
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backups:/data/backups
    networks:
      - remnawave-network

networks:
  remnawave-network:
    name: remnawave-network
    external: true
